version: "2"
services:
  mongodb:
    image: mongo:3.4
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db/
  heyburrito:
    build: .
    ports:
      - "3333:3333"
      - "8080:8080"
    environment:
      - BOT_NAME=heyburrito
      - DATABASE_DRIVER=mongodb
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=heyburrito
      - "SLACK_API_TOKEN=redacted"
      - "SLACK_EMOJI_INC=:burrito:"
      - "SLACK_EMOJI_DEC=:rottenburrito:"
      - SLACK_DAILY_CAP=5
      - ENABLE_DECREMENT=false
    links:
      - mongodb
