version: "2"
services:
  mongodb:
    image: mongo:3.4
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db/
  heywaffle:
    build:
      context: ./
    ports:
      - "3333:443"
      - "8080:8080"
    environment:
      - BOT_NAME=heywaffle
      - DATABASE_DRIVER=mongodb
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=heywaffle
      - SLACK_API_TOKEN=SeeDocumentation
      - "SLACK_EMOJI_INC=:waffle:"
      - SLACK_DAILY_CAP=5
      - WEB_PATH=/leaderboard/
      - THEME_URL=heywaffle-theme
    links:
      - mongodb
