apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heyburrito.fullname" . }}
  labels:
    {{- include "heyburrito.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_URL:  {{ include "heyburrito.mongodb.url" . | b64enc | quote }}
